-- Auto-generated by scripts/generate-seed-sql.ts — do not edit by hand.
-- Re-running this file is safe: categories/prompts are upserted by slug.

insert into public.categories (slug, name_ar, name_en, icon, sort_order) values
  ('product-shots', 'تصوير منتجات', 'Product Shots', 'package', 1),
  ('social-ads', 'إعلانات سوشيال ميديا', 'Social Media Ads', 'megaphone', 2),
  ('branding-logos', 'هوية بصرية ولوجوهات', 'Branding & Logos', 'sparkles', 3),
  ('portraits', 'بورتريه واقعي', 'Realistic Portraits', 'user', 4),
  ('art-styles', 'أنماط فنية', 'Art Styles', 'palette', 5),
  ('covers-posts', 'أغلفة ومنشورات', 'Covers & Posts', 'layout', 6),
  ('occasions', 'مناسبات', 'Occasions', 'calendar', 7)
on conflict (slug) do update set name_ar = excluded.name_ar, name_en = excluded.name_en, icon = excluded.icon, sort_order = excluded.sort_order;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'studio-product-white-bg', 'منتج على خلفية بيضاء احترافية', 'Product on a Clean White Studio Background',
  'صورة منتج نظيفة لصفحات المتجر والكتالوجات', 'Clean e-commerce style product photo for store listings',
  'professional studio product photography of {{product}}, centered composition, pure white seamless background, soft diffused lighting, subtle shadow beneath the product, high detail, commercial e-commerce style, 4k', 'تصوير منتج احترافي في استوديو لـ {{product}}، تكوين مركزي، خلفية بيضاء ناصعة بلا حواف، إضاءة ناعمة موزعة، ظل خفيف أسفل المنتج، تفاصيل عالية، أسلوب تجاري للمتاجر الإلكترونية، دقة 4K',
  '[{"key":"product","label_ar":"المنتج","label_en":"Product","default":"a glass perfume bottle"}]'::jsonb,
  (select id from public.categories where slug = 'product-shots'),
  'studio', 'flux-schnell', ARRAY['منتجات', 'متجر', 'product']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'product-lifestyle-scene', 'منتج في مشهد حياتي طبيعي', 'Product in a Lifestyle Scene',
  'منتج ضمن بيئة واقعية تعكس استخدامه اليومي', 'Product placed in a realistic everyday setting',
  'lifestyle product photography, {{product}} placed on a {{surface}}, natural window light, warm cozy atmosphere, shallow depth of field, editorial commercial photography, realistic textures', 'تصوير منتج بأسلوب حياتي، {{product}} موضوع على {{surface}}، إضاءة نافذة طبيعية، أجواء دافئة ومريحة، عمق ميدان ضحل، تصوير تجاري تحريري، خامات واقعية',
  '[{"key":"product","label_ar":"المنتج","label_en":"Product","default":"a ceramic coffee cup"},{"key":"surface","label_ar":"السطح","label_en":"Surface","default":"wooden breakfast table"}]'::jsonb,
  (select id from public.categories where slug = 'product-shots'),
  'lifestyle', 'flux-schnell', ARRAY['منتجات', 'lifestyle']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'product-floating-levitation', 'منتج عائم بتأثير الجاذبية الصفرية', 'Levitating Product Shot',
  'منتج يطفو في الهواء بتأثير بصري جذاب للإعلانات', 'Eye-catching floating product effect for ads',
  '{{product}} levitating in mid-air, zero gravity effect, dynamic scattered elements around it, dramatic studio lighting, gradient {{background_color}} background, high-end advertising photography, sharp focus', '{{product}} يطفو في الهواء، تأثير انعدام الجاذبية، عناصر متناثرة ديناميكية حوله، إضاءة استوديو درامية، خلفية متدرجة باللون {{background_color}}، تصوير إعلاني راقٍ، تركيز حاد',
  '[{"key":"product","label_ar":"المنتج","label_en":"Product","default":"a sneaker"},{"key":"background_color","label_ar":"لون الخلفية","label_en":"Background color","default":"deep purple"}]'::jsonb,
  (select id from public.categories where slug = 'product-shots'),
  'dramatic', 'flux-schnell', ARRAY['منتجات', 'إعلان']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'product-flatlay-top-down', 'تنسيق منتجات من الأعلى (Flat Lay)', 'Top-Down Flat Lay Arrangement',
  'تنسيق أنيق للمنتجات من زاوية علوية لمنشورات السوشيال ميديا', 'Elegant top-down arrangement for social media posts',
  'flat lay photography from directly above, {{product}} arranged neatly with {{props}}, {{background_color}} background, soft natural light, minimal aesthetic, symmetrical composition, high resolution', 'تصوير من الأعلى مباشرة (Flat Lay)، {{product}} مرتب بعناية مع {{props}}، خلفية {{background_color}}، إضاءة طبيعية ناعمة، تصميم بسيط أنيق، تكوين متماثل، دقة عالية',
  '[{"key":"product","label_ar":"المنتج","label_en":"Product","default":"skincare bottles"},{"key":"props","label_ar":"إكسسوارات مرافقة","label_en":"Props","default":"dried flowers and a linen towel"},{"key":"background_color","label_ar":"لون الخلفية","label_en":"Background color","default":"beige"}]'::jsonb,
  (select id from public.categories where slug = 'product-shots'),
  'minimal', 'flux-schnell', ARRAY['منتجات', 'flatlay']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'product-hand-holding', 'منتج ممسوك باليد', 'Product Held in Hand',
  'لقطة قريبة تُظهر حجم المنتج وملمسه بشكل واقعي', 'Close-up shot showing the product''s scale and texture',
  'close-up photo of a hand holding {{product}}, natural skin tones, soft daylight, blurred background, authentic unboxing style, high detail texture', 'لقطة قريبة ليد تمسك {{product}}، ألوان بشرة طبيعية، ضوء نهار ناعم، خلفية ضبابية، أسلوب فتح الصندوق الواقعي، تفاصيل خامة عالية',
  '[{"key":"product","label_ar":"المنتج","label_en":"Product","default":"a smartphone box"}]'::jsonb,
  (select id from public.categories where slug = 'product-shots'),
  'lifestyle', 'flux-schnell', ARRAY['منتجات', 'unboxing']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'product-splash-liquid', 'منتج مع تناثر سائل', 'Product with Liquid Splash',
  'تأثير بصري قوي لمنتجات المشروبات ومستحضرات التجميل', 'Dramatic splash effect for beverages and cosmetics',
  '{{product}} with dynamic {{liquid}} splash frozen in motion around it, dark studio background, dramatic rim lighting, high speed photography, crisp water droplets, commercial quality', '{{product}} مع تناثر {{liquid}} متجمد أثناء الحركة حوله، خلفية استوديو داكنة، إضاءة حافة درامية، تصوير عالي السرعة، قطرات ماء واضحة، جودة تجارية',
  '[{"key":"product","label_ar":"المنتج","label_en":"Product","default":"a cosmetic jar"},{"key":"liquid","label_ar":"السائل","label_en":"Liquid","default":"milk"}]'::jsonb,
  (select id from public.categories where slug = 'product-shots'),
  'dramatic', 'flux-schnell', ARRAY['منتجات', 'splash']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'product-packaging-mockup', 'موك أب تغليف المنتج', 'Product Packaging Mockup',
  'عرض واقعي لعلبة أو تغليف المنتج قبل الطباعة', 'Realistic mockup of product packaging before printing',
  'realistic packaging mockup of {{product}} box, {{color}} design, placed on a clean surface, soft studio lighting, subtle reflection, front-facing angle, high resolution product render', 'موك أب واقعي لعلبة تغليف {{product}}، تصميم بلون {{color}}، موضوعة على سطح نظيف، إضاءة استوديو ناعمة، انعكاس خفيف، زاوية أمامية، عرض منتج بدقة عالية',
  '[{"key":"product","label_ar":"المنتج","label_en":"Product","default":"a snack"},{"key":"color","label_ar":"اللون الأساسي","label_en":"Primary color","default":"green and gold"}]'::jsonb,
  (select id from public.categories where slug = 'product-shots'),
  'studio', 'flux-schnell', ARRAY['منتجات', 'تغليف']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'product-outdoor-natural', 'منتج في بيئة خارجية طبيعية', 'Product in an Outdoor Natural Setting',
  'منتج بمظهر طبيعي خارجي يناسب منتجات العناية والطبيعة', 'Natural outdoor look, suited for organic and wellness products',
  '{{product}} placed among natural elements like stones and green leaves, outdoor golden hour lighting, organic earthy tones, shallow depth of field, editorial nature photography', '{{product}} موضوع وسط عناصر طبيعية كالحجارة وأوراق الشجر، إضاءة الساعة الذهبية الخارجية، ألوان ترابية طبيعية، عمق ميدان ضحل، تصوير طبيعي تحريري',
  '[{"key":"product","label_ar":"المنتج","label_en":"Product","default":"an organic soap bar"}]'::jsonb,
  (select id from public.categories where slug = 'product-shots'),
  'natural', 'flux-schnell', ARRAY['منتجات', 'طبيعي']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'product-360-catalog', 'منتج بزاوية ثلاثة أرباع للكتالوج', 'Three-Quarter Angle Catalog Shot',
  'زاوية كتالوجية كلاسيكية تُظهر أبعاد المنتج', 'Classic catalog angle showing the product''s dimensions',
  'three-quarter angle product photo of {{product}}, light gray gradient background, even studio lighting, sharp focus, no harsh shadows, catalog ready, professional retouching', 'صورة منتج بزاوية ثلاثة أرباع لـ {{product}}، خلفية متدرجة رمادية فاتحة، إضاءة استوديو متساوية، تركيز حاد، بلا ظلال قاسية، جاهزة للكتالوج، معالجة احترافية',
  '[{"key":"product","label_ar":"المنتج","label_en":"Product","default":"a leather handbag"}]'::jsonb,
  (select id from public.categories where slug = 'product-shots'),
  'studio', 'flux-schnell', ARRAY['منتجات', 'كتالوج']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'product-color-variants-grid', 'شبكة تدرجات ألوان المنتج', 'Product Color Variants Grid',
  'عرض منظم لتدرجات ألوان المنتج المتوفرة', 'Organized display of the product''s available color options',
  'clean grid layout showing {{product}} in three different color variants, consistent studio lighting, plain white background, evenly spaced arrangement, e-commerce variant showcase style', 'تخطيط شبكي نظيف يعرض {{product}} بثلاثة تدرجات ألوان مختلفة، إضاءة استوديو ثابتة، خلفية بيضاء بسيطة، ترتيب متساوي المسافات، أسلوب عرض خيارات المتجر الإلكتروني',
  '[{"key":"product","label_ar":"المنتج","label_en":"Product","default":"a wireless earbuds case"}]'::jsonb,
  (select id from public.categories where slug = 'product-shots'),
  'studio', 'flux-schnell', ARRAY['منتجات', 'متغيرات']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'instagram-square-promo', 'منشور ترويجي مربع لإنستغرام', 'Square Instagram Promo Post',
  'تصميم إعلاني جذاب بمقاس مربع لمنشورات إنستغرام', 'Bold square-format ad visual for Instagram feed',
  'square format social media advertisement for {{business}}, bold {{color}} color scheme, large empty space for text overlay, modern flat design, high contrast, eye-catching, marketing poster style', 'إعلان سوشيال ميديا بمقاس مربع لـ {{business}}، ألوان جريئة بلون {{color}}، مساحة فارغة كبيرة لإضافة نص، تصميم مسطح عصري، تباين عالٍ، لافت للنظر، أسلوب بوستر تسويقي',
  '[{"key":"business","label_ar":"النشاط التجاري","label_en":"Business","default":"a coffee shop"},{"key":"color","label_ar":"اللون الأساسي","label_en":"Primary color","default":"orange and cream"}]'::jsonb,
  (select id from public.categories where slug = 'social-ads'),
  'flat design', 'flux-schnell', ARRAY['إعلان', 'سوشيال ميديا']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'sale-discount-banner', 'بانر تخفيضات وعروض', 'Sale & Discount Banner',
  'بانر إعلاني حماسي لعروض التخفيضات الموسمية', 'Energetic banner design for seasonal discount campaigns',
  'vibrant sale banner design, big bold ''{{discount}}'' text placeholder area, dynamic diagonal shapes, {{color}} gradient background, confetti and burst elements, exciting retail promotion style', 'تصميم بانر تخفيضات نابض بالحياة، مساحة نصية كبيرة وجريئة لنسبة الخصم ''{{discount}}''، أشكال قطرية ديناميكية، خلفية متدرجة بلون {{color}}، عناصر قصاصات ورقية واحتفالية، أسلوب ترويجي حماسي للتجزئة',
  '[{"key":"discount","label_ar":"نسبة الخصم","label_en":"Discount","default":"50% OFF"},{"key":"color","label_ar":"لون الخلفية","label_en":"Background color","default":"red and yellow"}]'::jsonb,
  (select id from public.categories where slug = 'social-ads'),
  'bold', 'flux-schnell', ARRAY['إعلان', 'تخفيضات']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'app-feature-mockup', 'عرض ميزة تطبيق على جهاز', 'App Feature Mockup on Device',
  'عرض واجهة تطبيق على شاشة هاتف بأسلوب تسويقي أنيق', 'Elegant marketing display of an app screen on a phone mockup',
  'modern smartphone mockup floating at an angle, displaying a clean {{app_type}} app interface, soft gradient {{color}} background, subtle shadow, tech marketing style, minimal and premium', 'موك أب هاتف ذكي عصري معلق بزاوية، يعرض واجهة تطبيق {{app_type}} نظيفة، خلفية متدرجة ناعمة بلون {{color}}، ظل خفيف، أسلوب تسويقي تقني، بسيط وراقٍ',
  '[{"key":"app_type","label_ar":"نوع التطبيق","label_en":"App type","default":"food delivery"},{"key":"color","label_ar":"لون الخلفية","label_en":"Background color","default":"blue and white"}]'::jsonb,
  (select id from public.categories where slug = 'social-ads'),
  'tech', 'flux-schnell', ARRAY['إعلان', 'تطبيقات']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'before-after-split', 'مقارنة قبل وبعد', 'Before & After Split Visual',
  'تصميم مقسوم يعرض نتائج الخدمة أو المنتج بوضوح', 'Split-screen design clearly showcasing service or product results',
  'split screen comparison image, left side showing {{before}}, right side showing {{after}}, clean dividing line, bright even lighting, professional before-and-after marketing layout', 'صورة مقارنة مقسومة الشاشة، الجانب الأيسر يُظهر {{before}}، الجانب الأيمن يُظهر {{after}}، خط فاصل نظيف، إضاءة ساطعة ومتساوية، تخطيط تسويقي احترافي لقبل وبعد',
  '[{"key":"before","label_ar":"الحالة قبل","label_en":"Before state","default":"a dull faded car exterior"},{"key":"after","label_ar":"الحالة بعد","label_en":"After state","default":"the same car, polished and glossy"}]'::jsonb,
  (select id from public.categories where slug = 'social-ads'),
  'clean', 'flux-schnell', ARRAY['إعلان', 'قبل وبعد']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'testimonial-quote-card', 'بطاقة رأي عميل', 'Customer Testimonial Card',
  'بطاقة أنيقة لعرض تقييمات وآراء العملاء', 'Elegant card layout for displaying customer reviews',
  'elegant testimonial card background design, soft {{color}} pastel tones, large quotation mark graphic, star rating icons, minimal clean layout with space for text, professional social proof style', 'خلفية بطاقة تقييم عملاء أنيقة، درجات لون {{color}} هادئة، رمز علامة اقتباس كبيرة، أيقونات تقييم بالنجوم، تخطيط بسيط ونظيف مع مساحة للنص، أسلوب احترافي لعرض الثقة الاجتماعية',
  '[{"key":"color","label_ar":"اللون","label_en":"Color","default":"soft blue"}]'::jsonb,
  (select id from public.categories where slug = 'social-ads'),
  'minimal', 'flux-schnell', ARRAY['إعلان', 'تقييمات']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'story-countdown-launch', 'ستوري عد تنازلي لإطلاق منتج', 'Countdown Story for Product Launch',
  'تصميم ستوري رأسي مثير يعلن عن اقتراب إطلاق جديد', 'Vertical story design building excitement for a new launch',
  'vertical story format design, dramatic countdown timer graphic, dark {{color}} background with glowing particles, teaser text space, futuristic launch announcement style, high energy', 'تصميم ستوري بصيغة رأسية، رسم عداد تنازلي درامي، خلفية داكنة بلون {{color}} مع جزيئات متوهجة، مساحة نص تشويقي، أسلوب إعلان إطلاق مستقبلي، طاقة عالية',
  '[{"key":"color","label_ar":"لون الخلفية","label_en":"Background color","default":"midnight blue"}]'::jsonb,
  (select id from public.categories where slug = 'social-ads'),
  'futuristic', 'flux-schnell', ARRAY['إعلان', 'ستوري']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'carousel-tips-slide', 'شريحة كاروسيل نصائح', 'Carousel Tips Slide',
  'تصميم شريحة موحدة لمنشورات الكاروسيل التعليمية', 'Cohesive slide design for educational carousel posts',
  'clean educational carousel slide design, bold number ''{{number}}'' graphic element, {{color}} background with soft geometric shapes, generous text space, modern infographic style', 'تصميم شريحة كاروسيل تعليمية نظيفة، عنصر رقم ''{{number}}'' بارز، خلفية بلون {{color}} مع أشكال هندسية ناعمة، مساحة نص واسعة، أسلوب إنفوجرافيك عصري',
  '[{"key":"number","label_ar":"الرقم","label_en":"Number","default":"1"},{"key":"color","label_ar":"لون الخلفية","label_en":"Background color","default":"teal"}]'::jsonb,
  (select id from public.categories where slug = 'social-ads'),
  'infographic', 'flux-schnell', ARRAY['إعلان', 'كاروسيل']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'limited-stock-urgency', 'تصميم إلحاح الكمية المحدودة', 'Limited Stock Urgency Design',
  'تصميم يحفّز الشراء الفوري بشعور الندرة', 'Design that drives urgency and immediate purchase action',
  'urgent retail promotion design, ''{{message}}'' bold typography placeholder, warning stripe pattern accents, {{color}} high alert color scheme, dynamic energetic composition', 'تصميم ترويجي عاجل للتجزئة، مساحة نصية بارزة لعبارة ''{{message}}''، لمسات نمط خطوط تحذيرية، تدرج ألوان {{color}} عالي التنبيه، تكوين ديناميكي حيوي',
  '[{"key":"message","label_ar":"الرسالة","label_en":"Message","default":"LAST CHANCE"},{"key":"color","label_ar":"اللون","label_en":"Color","default":"red and black"}]'::jsonb,
  (select id from public.categories where slug = 'social-ads'),
  'bold', 'flux-schnell', ARRAY['إعلان', 'عرض محدود']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'gift-guide-ad', 'إعلان دليل هدايا', 'Gift Guide Ad',
  'تصميم دافئ يعرض تشكيلة هدايا لمناسبة معينة', 'Warm design showcasing a curated gift collection',
  'cozy gift guide advertisement featuring {{items}} arranged elegantly, warm {{color}} festive palette, soft ribbon and wrapping paper details, inviting shopping campaign style', 'إعلان دليل هدايا دافئ يعرض {{items}} مرتبة بأناقة، لوحة ألوان احتفالية دافئة {{color}}، تفاصيل شرائط وورق تغليف ناعمة، أسلوب حملة تسوق جذابة',
  '[{"key":"items","label_ar":"الهدايا","label_en":"Gift items","default":"perfume bottles and gift boxes"},{"key":"color","label_ar":"الألوان","label_en":"Colors","default":"burgundy and gold"}]'::jsonb,
  (select id from public.categories where slug = 'social-ads'),
  'festive', 'flux-schnell', ARRAY['إعلان', 'هدايا']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'review-highlight-card', 'بطاقة إبراز تقييم مميز', 'Review Highlight Card',
  'تصميم يبرز تقييماً بارزاً لبناء الثقة', 'Design highlighting a standout review to build trust',
  'eye-catching review highlight card design, five gold stars prominently displayed, soft {{color}} background, quotation accent graphic, clean modern layout with space for review text', 'تصميم بطاقة إبراز تقييم لافت، خمس نجوم ذهبية بارزة، خلفية ناعمة بلون {{color}}، لمسة رسومية لعلامة اقتباس، تخطيط عصري نظيف مع مساحة لنص التقييم',
  '[{"key":"color","label_ar":"لون الخلفية","label_en":"Background color","default":"mint green"}]'::jsonb,
  (select id from public.categories where slug = 'social-ads'),
  'minimal', 'flux-schnell', ARRAY['إعلان', 'تقييمات']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'minimal-lettermark-logo', 'لوجو حرفي بسيط', 'Minimal Lettermark Logo',
  'شعار أنيق مبني على الحرف الأول من اسم العلامة', 'Elegant logo built around the brand''s initial letter',
  'minimal lettermark logo design featuring the letter ''{{letter}}'', geometric clean lines, {{color}} color palette, flat vector style, centered on plain white background, modern brand identity', 'تصميم لوجو حرفي بسيط يعتمد على الحرف ''{{letter}}''، خطوط هندسية نظيفة، لوحة ألوان {{color}}، أسلوب فيكتور مسطح، في وسط خلفية بيضاء بسيطة، هوية علامة تجارية عصرية',
  '[{"key":"letter","label_ar":"الحرف","label_en":"Letter","default":"N"},{"key":"color","label_ar":"الألوان","label_en":"Colors","default":"navy and gold"}]'::jsonb,
  (select id from public.categories where slug = 'branding-logos'),
  'flat vector', 'flux-schnell', ARRAY['لوجو', 'هوية']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'abstract-mark-logo', 'شعار رمزي تجريدي', 'Abstract Symbol Mark',
  'رمز تجريدي يعكس مفهوم النشاط التجاري', 'Abstract symbol representing the brand''s concept',
  'abstract geometric logo mark representing {{concept}}, minimal flat vector shapes, {{color}} gradient, balanced negative space, professional brand mark on white background', 'شعار هندسي تجريدي يمثل مفهوم {{concept}}، أشكال فيكتور مسطحة بسيطة، تدرج لوني {{color}}، توازن في المساحات الفارغة، علامة تجارية احترافية على خلفية بيضاء',
  '[{"key":"concept","label_ar":"المفهوم","label_en":"Concept","default":"growth and connection"},{"key":"color","label_ar":"التدرج اللوني","label_en":"Gradient","default":"green to blue"}]'::jsonb,
  (select id from public.categories where slug = 'branding-logos'),
  'abstract', 'flux-schnell', ARRAY['لوجو', 'تجريدي']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'mascot-character-logo', 'شعار شخصية كرتونية (ماسكوت)', 'Mascot Character Logo',
  'شخصية ودودة تمثل العلامة التجارية بأسلوب كرتوني', 'Friendly character representing the brand in cartoon style',
  'friendly cartoon mascot logo of a {{animal}}, bold outlines, flat vibrant {{color}} colors, playful expression, centered vector illustration on white background, brand mascot style', 'شعار ماسكوت كرتوني ودود على شكل {{animal}}، خطوط خارجية بارزة، ألوان مسطحة زاهية {{color}}، تعبير مرح، رسم فيكتور في المنتصف على خلفية بيضاء، أسلوب ماسكوت للعلامة التجارية',
  '[{"key":"animal","label_ar":"الحيوان","label_en":"Animal","default":"a fox"},{"key":"color","label_ar":"الألوان","label_en":"Colors","default":"orange and white"}]'::jsonb,
  (select id from public.categories where slug = 'branding-logos'),
  'mascot', 'flux-schnell', ARRAY['لوجو', 'ماسكوت']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'emblem-badge-logo', 'شعار شارة تقليدية (إمبلم)', 'Classic Emblem Badge Logo',
  'شعار دائري كلاسيكي يوحي بالثقة والتراث', 'Classic circular badge conveying trust and heritage',
  'vintage emblem badge logo design for {{business}}, circular border with ornamental details, {{color}} monochrome palette, centered icon of {{icon}}, flat vector illustration on white background', 'تصميم شعار شارة كلاسيكية (إمبلم) لـ {{business}}، حدود دائرية بتفاصيل زخرفية، لوحة ألوان أحادية {{color}}، أيقونة مركزية لـ {{icon}}، رسم فيكتور على خلفية بيضاء',
  '[{"key":"business","label_ar":"النشاط التجاري","label_en":"Business","default":"a coffee roastery"},{"key":"icon","label_ar":"الرمز المركزي","label_en":"Central icon","default":"a coffee bean"},{"key":"color","label_ar":"اللون","label_en":"Color","default":"dark brown"}]'::jsonb,
  (select id from public.categories where slug = 'branding-logos'),
  'emblem', 'flux-schnell', ARRAY['لوجو', 'شارة']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'brand-color-palette-board', 'لوحة ألوان الهوية البصرية', 'Brand Color Palette Board',
  'عرض منظم لألوان الهوية البصرية للعلامة', 'Organized presentation of the brand''s color identity',
  'clean brand style guide color palette board, five color swatches in {{color}} tones arranged horizontally, minimal typography labels, professional branding presentation layout, white background', 'لوحة عرض ألوان دليل الهوية البصرية بتصميم نظيف، خمس عينات ألوان بدرجات {{color}} مرتبة أفقياً، تسميات نصية بسيطة، تخطيط عرض احترافي للهوية، خلفية بيضاء',
  '[{"key":"color","label_ar":"الدرجات اللونية","label_en":"Color tones","default":"warm earthy"}]'::jsonb,
  (select id from public.categories where slug = 'branding-logos'),
  'presentation', 'flux-schnell', ARRAY['هوية', 'ألوان']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'business-card-mockup', 'موك أب بطاقة عمل', 'Business Card Mockup',
  'عرض واقعي لتصميم بطاقة العمل على سطح أنيق', 'Realistic mockup of a business card design on an elegant surface',
  'realistic business card mockup, two cards with a {{color}} minimal design, placed on a {{surface}}, soft natural lighting, shallow depth of field, professional branding photography', 'موك أب واقعي لبطاقة عمل، بطاقتان بتصميم بسيط بلون {{color}}، موضوعتان على {{surface}}، إضاءة طبيعية ناعمة، عمق ميدان ضحل، تصوير هوية بصرية احترافي',
  '[{"key":"color","label_ar":"اللون","label_en":"Color","default":"black and gold"},{"key":"surface","label_ar":"السطح","label_en":"Surface","default":"a marble table"}]'::jsonb,
  (select id from public.categories where slug = 'branding-logos'),
  'mockup', 'flux-schnell', ARRAY['هوية', 'بطاقة عمل']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'storefront-signage-mockup', 'موك أب لافتة واجهة متجر', 'Storefront Signage Mockup',
  'عرض الشعار على واجهة متجر واقعية', 'Logo displayed on a realistic store front',
  'realistic storefront signage mockup for {{business}}, modern shop exterior, clean {{color}} signage board with logo placeholder, daytime natural lighting, architectural photography style', 'موك أب واقعي للافتة واجهة متجر لـ {{business}}، واجهة محل عصرية، لوحة لافتة نظيفة بلون {{color}} مع مساحة للشعار، إضاءة نهارية طبيعية، أسلوب تصوير معماري',
  '[{"key":"business","label_ar":"النشاط التجاري","label_en":"Business","default":"a bakery"},{"key":"color","label_ar":"لون اللافتة","label_en":"Signage color","default":"warm cream and wood"}]'::jsonb,
  (select id from public.categories where slug = 'branding-logos'),
  'mockup', 'flux-schnell', ARRAY['هوية', 'واجهة متجر']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'app-icon-design', 'تصميم أيقونة تطبيق', 'App Icon Design',
  'أيقونة تطبيق حديثة بزوايا دائرية وألوان متدرجة', 'Modern rounded app icon with gradient colors',
  'modern mobile app icon design, rounded square shape, simple {{symbol}} symbol centered, smooth {{color}} gradient background, flat minimal style, iOS app store quality', 'تصميم أيقونة تطبيق جوال عصرية، شكل مربع بزوايا دائرية، رمز {{symbol}} بسيط في المنتصف، خلفية متدرجة ناعمة بلون {{color}}، أسلوب مسطح بسيط، بجودة متجر التطبيقات',
  '[{"key":"symbol","label_ar":"الرمز","label_en":"Symbol","default":"a chat bubble"},{"key":"color","label_ar":"التدرج اللوني","label_en":"Gradient","default":"purple to pink"}]'::jsonb,
  (select id from public.categories where slug = 'branding-logos'),
  'flat design', 'flux-schnell', ARRAY['هوية', 'أيقونة']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'letterhead-mockup', 'موك أب ورق رسمي (Letterhead)', 'Letterhead Mockup',
  'عرض واقعي لتصميم الورق الرسمي للمراسلات', 'Realistic mockup of official correspondence stationery',
  'realistic letterhead mockup for {{business}}, minimal {{color}} header design with logo placeholder, clean paper texture, top-down flat lay photography, professional stationery presentation', 'موك أب واقعي لورق رسمي لـ{{business}}، تصميم ترويسة بسيط بلون {{color}} مع مساحة للشعار، خامة ورق نظيفة، تصوير من الأعلى، عرض قرطاسية احترافي',
  '[{"key":"business","label_ar":"النشاط التجاري","label_en":"Business","default":"a law firm"},{"key":"color","label_ar":"اللون","label_en":"Color","default":"navy blue"}]'::jsonb,
  (select id from public.categories where slug = 'branding-logos'),
  'mockup', 'flux-schnell', ARRAY['هوية', 'قرطاسية']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'corporate-headshot', 'صورة شخصية احترافية للأعمال', 'Professional Corporate Headshot',
  'صورة بورتريه رسمية تناسب الملفات الشخصية المهنية', 'Formal portrait suited for professional profiles',
  'professional corporate headshot portrait of a {{person}}, wearing {{outfit}}, neutral gray studio background, soft even lighting, confident expression, sharp focus, high-end photography', 'صورة بورتريه احترافية لـ{{person}}، يرتدي {{outfit}}، خلفية استوديو رمادية محايدة، إضاءة ناعمة متساوية، تعبير واثق، تركيز حاد، تصوير راقٍ',
  '[{"key":"person","label_ar":"الشخص","label_en":"Person","default":"a businesswoman"},{"key":"outfit","label_ar":"الزي","label_en":"Outfit","default":"a tailored navy blazer"}]'::jsonb,
  (select id from public.categories where slug = 'portraits'),
  'corporate', 'flux-schnell', ARRAY['بورتريه', 'أعمال']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'cinematic-outdoor-portrait', 'بورتريه سينمائي خارجي', 'Cinematic Outdoor Portrait',
  'بورتريه بإضاءة الغروب وأجواء سينمائية', 'Portrait with golden hour lighting and cinematic mood',
  'cinematic portrait of a {{person}}, golden hour sunset lighting, warm rim light, shallow depth of field, blurred outdoor background, film grain, moody atmosphere, professional photography', 'بورتريه سينمائي لـ{{person}}، إضاءة غروب الشمس الذهبية، ضوء حافة دافئ، عمق ميدان ضحل، خلفية خارجية ضبابية، حبيبات فيلم، أجواء درامية، تصوير احترافي',
  '[{"key":"person","label_ar":"الشخص","label_en":"Person","default":"a young man"}]'::jsonb,
  (select id from public.categories where slug = 'portraits'),
  'cinematic', 'flux-schnell', ARRAY['بورتريه', 'سينمائي']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'studio-beauty-portrait', 'بورتريه تجميلي في الاستوديو', 'Studio Beauty Portrait',
  'بورتريه ناعم يبرز نضارة البشرة لإعلانات التجميل', 'Soft glowing portrait highlighting skin, ideal for beauty ads',
  'beauty studio portrait of a {{person}}, flawless glowing skin, soft beauty dish lighting, clean {{background_color}} background, minimal makeup, sharp detailed close-up, cosmetics advertising style', 'بورتريه تجميلي في الاستوديو لـ{{person}}، بشرة نضرة خالية من العيوب، إضاءة طبق تجميل ناعمة، خلفية نظيفة بلون {{background_color}}، مكياج بسيط، لقطة قريبة حادة التفاصيل، أسلوب إعلانات مستحضرات التجميل',
  '[{"key":"person","label_ar":"الشخص","label_en":"Person","default":"a woman"},{"key":"background_color","label_ar":"لون الخلفية","label_en":"Background color","default":"soft pink"}]'::jsonb,
  (select id from public.categories where slug = 'portraits'),
  'beauty', 'flux-schnell', ARRAY['بورتريه', 'تجميل']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'traditional-attire-portrait', 'بورتريه بالزي التراثي', 'Traditional Attire Portrait',
  'بورتريه يبرز الزي التراثي الخليجي بإضاءة فاخرة', 'Portrait highlighting traditional Gulf attire with elegant lighting',
  'elegant portrait of a {{person}} wearing traditional {{attire}}, rich warm lighting, ornate patterned background, detailed fabric texture, cultural photography, high production quality', 'بورتريه أنيق لـ{{person}} يرتدي {{attire}} التراثي، إضاءة دافئة فاخرة، خلفية بزخارف مزركشة، تفاصيل قماش دقيقة، تصوير ثقافي، جودة إنتاج عالية',
  '[{"key":"person","label_ar":"الشخص","label_en":"Person","default":"a man"},{"key":"attire","label_ar":"الزي","label_en":"Attire","default":"a bisht over a white thobe"}]'::jsonb,
  (select id from public.categories where slug = 'portraits'),
  'cultural', 'flux-schnell', ARRAY['بورتريه', 'تراث']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'candid-lifestyle-portrait', 'بورتريه عفوي بأسلوب حياتي', 'Candid Lifestyle Portrait',
  'لحظة طبيعية غير مصطنعة تناسب المحتوى الشخصي', 'A natural unposed moment, great for personal content',
  'candid lifestyle portrait of a {{person}} laughing naturally at {{location}}, soft natural daylight, authentic unposed moment, warm color grading, documentary photography style', 'بورتريه عفوي بأسلوب حياتي لـ{{person}} يضحك بشكل طبيعي في {{location}}، ضوء نهار طبيعي ناعم، لحظة أصيلة غير مصطنعة، تدرج ألوان دافئ، أسلوب تصوير وثائقي',
  '[{"key":"person","label_ar":"الشخص","label_en":"Person","default":"a young woman"},{"key":"location","label_ar":"المكان","label_en":"Location","default":"a busy souq"}]'::jsonb,
  (select id from public.categories where slug = 'portraits'),
  'candid', 'flux-schnell', ARRAY['بورتريه', 'حياتي']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'dramatic-black-white-portrait', 'بورتريه درامي بالأبيض والأسود', 'Dramatic Black & White Portrait',
  'بورتريه فني كلاسيكي بتباين قوي وظلال درامية', 'Classic artistic portrait with strong contrast and dramatic shadows',
  'dramatic black and white portrait of a {{person}}, strong directional side lighting, deep shadows, high contrast, fine art photography style, sharp detailed eyes, timeless mood', 'بورتريه درامي بالأبيض والأسود لـ{{person}}، إضاءة جانبية قوية موجهة، ظلال عميقة، تباين عالٍ، أسلوب تصوير فني كلاسيكي، عينان حادتا التفاصيل، أجواء خالدة',
  '[{"key":"person","label_ar":"الشخص","label_en":"Person","default":"an elderly man"}]'::jsonb,
  (select id from public.categories where slug = 'portraits'),
  'fine art', 'flux-schnell', ARRAY['بورتريه', 'أبيض وأسود']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'family-group-portrait', 'بورتريه عائلي جماعي', 'Family Group Portrait',
  'صورة جماعية دافئة تناسب المناسبات العائلية', 'Warm group photo suited for family occasions',
  'warm family group portrait of {{group}}, soft golden hour outdoor lighting, natural genuine smiles, coordinated {{color}} outfit tones, professional family photography style', 'بورتريه عائلي جماعي دافئ لـ{{group}}، إضاءة خارجية ذهبية ناعمة، ابتسامات طبيعية صادقة، ألوان ملابس منسقة {{color}}، أسلوب تصوير عائلي احترافي',
  '[{"key":"group","label_ar":"أفراد العائلة","label_en":"Family members","default":"a family of four"},{"key":"color","label_ar":"ألوان الملابس","label_en":"Outfit colors","default":"beige and white"}]'::jsonb,
  (select id from public.categories where slug = 'portraits'),
  'lifestyle', 'flux-schnell', ARRAY['بورتريه', 'عائلي']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'team-corporate-portrait', 'بورتريه فريق العمل', 'Corporate Team Portrait',
  'صورة جماعية احترافية لفريق العمل داخل المكتب', 'Professional group photo of a team inside the office',
  'professional corporate team portrait of {{team_size}} colleagues, modern office background, bright even lighting, confident friendly poses, business casual attire, high-end corporate photography', 'بورتريه احترافي لفريق عمل مكوّن من {{team_size}}، خلفية مكتب عصري، إضاءة ساطعة متساوية، وضعيات واثقة وودية، زي عمل غير رسمي، تصوير مؤسسي راقٍ',
  '[{"key":"team_size","label_ar":"عدد أفراد الفريق","label_en":"Team size","default":"five"}]'::jsonb,
  (select id from public.categories where slug = 'portraits'),
  'corporate', 'flux-schnell', ARRAY['بورتريه', 'فريق عمل']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  '3d-render-character', 'شخصية برندر ثلاثي الأبعاد', '3D Rendered Character',
  'شخصية بأسلوب رندر ثلاثي الأبعاد ناعم وحديث', 'Character in a smooth modern 3D render style',
  'cute 3D rendered character of {{subject}}, smooth clay-like material, soft studio lighting, vibrant {{color}} colors, Pixar-inspired style, centered composition, high quality render', 'شخصية برندر ثلاثي الأبعاد لطيفة لـ{{subject}}، خامة ناعمة شبيهة بالصلصال، إضاءة استوديو ناعمة، ألوان زاهية {{color}}، أسلوب مستوحى من بيكسار، تكوين مركزي، رندر عالي الجودة',
  '[{"key":"subject","label_ar":"الموضوع","label_en":"Subject","default":"a small robot"},{"key":"color","label_ar":"الألوان","label_en":"Colors","default":"orange and teal"}]'::jsonb,
  (select id from public.categories where slug = 'art-styles'),
  '3D render', 'flux-schnell', ARRAY['فني', '3D']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'anime-style-scene', 'مشهد بأسلوب الأنمي', 'Anime Style Scene',
  'مشهد ملون بأسلوب رسوم الأنمي الياباني', 'Colorful scene drawn in Japanese anime art style',
  'anime style illustration of {{subject}}, vibrant cel-shaded colors, detailed line art, dramatic {{lighting}} lighting, Japanese animation aesthetic, dynamic composition', 'رسمة بأسلوب الأنمي لـ{{subject}}، ألوان زاهية بتظليل خلوي، رسم خطوط دقيق، إضاءة {{lighting}} درامية، جمالية الرسوم المتحركة اليابانية، تكوين ديناميكي',
  '[{"key":"subject","label_ar":"الموضوع","label_en":"Subject","default":"a warrior standing on a rooftop"},{"key":"lighting","label_ar":"الإضاءة","label_en":"Lighting","default":"sunset"}]'::jsonb,
  (select id from public.categories where slug = 'art-styles'),
  'anime', 'flux-schnell', ARRAY['فني', 'أنمي']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'cinematic-movie-still', 'لقطة سينمائية بأسلوب الأفلام', 'Cinematic Movie Still',
  'مشهد بجودة وأجواء لقطة فيلم سينمائي', 'Scene with the quality and mood of a film still',
  'cinematic movie still of {{scene}}, anamorphic lens flare, teal and orange color grading, dramatic atmosphere, wide aspect ratio composition, film grain, blockbuster quality', 'لقطة سينمائية من {{scene}}، توهج عدسة أنامورفيك، تدرج ألوان بين السماوي والبرتقالي، أجواء درامية، تكوين بنسبة عرض واسعة، حبيبات فيلم، جودة أفلام هوليوود',
  '[{"key":"scene","label_ar":"المشهد","label_en":"Scene","default":"a lone figure walking through a rainy city street at night"}]'::jsonb,
  (select id from public.categories where slug = 'art-styles'),
  'cinematic', 'flux-schnell', ARRAY['فني', 'سينمائي']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'watercolor-illustration', 'رسمة بألوان مائية', 'Watercolor Illustration',
  'رسمة ناعمة بأسلوب الألوان المائية اليدوية', 'Soft handmade-feel illustration in watercolor style',
  'delicate watercolor illustration of {{subject}}, soft flowing color bleeds, visible paper texture, pastel {{color}} tones, hand-painted artistic style, light and airy composition', 'رسمة ألوان مائية رقيقة لـ{{subject}}، سيولة ألوان ناعمة متداخلة، خامة ورق ظاهرة، درجات {{color}} باستيل، أسلوب فني مرسوم يدوياً، تكوين خفيف وهوائي',
  '[{"key":"subject","label_ar":"الموضوع","label_en":"Subject","default":"a bouquet of desert flowers"},{"key":"color","label_ar":"الألوان","label_en":"Colors","default":"warm terracotta"}]'::jsonb,
  (select id from public.categories where slug = 'art-styles'),
  'watercolor', 'flux-schnell', ARRAY['فني', 'ألوان مائية']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'isometric-illustration', 'رسمة إيزومترية', 'Isometric Illustration',
  'تصميم إيزومتري نظيف يناسب الشرح البصري والتقني', 'Clean isometric design great for tech and explainer visuals',
  'isometric illustration of {{scene}}, clean geometric shapes, flat vibrant colors, soft shadows, miniature diorama feel, modern tech illustration style', 'رسمة إيزومترية لـ{{scene}}، أشكال هندسية نظيفة، ألوان مسطحة زاهية، ظلال ناعمة، طابع الديوراما المصغرة، أسلوب رسم تقني عصري',
  '[{"key":"scene","label_ar":"المشهد","label_en":"Scene","default":"a small coffee shop interior"}]'::jsonb,
  (select id from public.categories where slug = 'art-styles'),
  'isometric', 'flux-schnell', ARRAY['فني', 'إيزومتري']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'arabic-calligraphy-art', 'لوحة خط عربي فني', 'Arabic Calligraphy Art',
  'تكوين فني معاصر مبني على الخط العربي', 'Contemporary artistic composition built on Arabic calligraphy',
  'artistic Arabic calligraphy composition of the word ''{{word}}'', elegant flowing script, gold ink accents on a {{color}} textured background, modern Islamic art style, high detail', 'لوحة خط عربي فنية لكلمة ''{{word}}''، خط انسيابي أنيق، لمسات حبر ذهبي على خلفية بخامة {{color}}، أسلوب فني إسلامي معاصر، تفاصيل عالية',
  '[{"key":"word","label_ar":"الكلمة","label_en":"Word","default":"بسم الله"},{"key":"color","label_ar":"لون الخلفية","label_en":"Background color","default":"deep emerald green"}]'::jsonb,
  (select id from public.categories where slug = 'art-styles'),
  'calligraphy', 'flux-schnell', ARRAY['فني', 'خط عربي']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'pop-art-portrait', 'بورتريه بأسلوب البوب آرت', 'Pop Art Style Portrait',
  'بورتريه ملون بأسلوب البوب آرت الجريء', 'Bold colorful portrait in the pop art style',
  'pop art style portrait of {{subject}}, bold flat {{color}} color blocks, thick black outlines, halftone dot pattern, Andy Warhol inspired aesthetic, high contrast graphic style', 'بورتريه بأسلوب البوب آرت لـ{{subject}}، كتل ألوان مسطحة جريئة {{color}}، خطوط خارجية سوداء سميكة، نمط نقاط هالفتون، جمالية مستوحاة من آندي وارهول، أسلوب رسومي عالي التباين',
  '[{"key":"subject","label_ar":"الموضوع","label_en":"Subject","default":"a woman"},{"key":"color","label_ar":"الألوان","label_en":"Colors","default":"hot pink and yellow"}]'::jsonb,
  (select id from public.categories where slug = 'art-styles'),
  'pop art', 'flux-schnell', ARRAY['فني', 'بوب آرت']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'cyberpunk-scene', 'مشهد سايبربانك مستقبلي', 'Cyberpunk Futuristic Scene',
  'مشهد مدينة مستقبلية بأضواء نيون ساطعة', 'A futuristic city scene lit with vivid neon lights',
  'cyberpunk futuristic scene of {{scene}}, glowing neon {{color}} lights, rain-soaked reflective streets, towering holographic signs, moody atmospheric fog, highly detailed digital art', 'مشهد سايبربانك مستقبلي لـ{{scene}}، أضواء نيون متوهجة {{color}}، شوارع مبللة عاكسة، لافتات هولوغرافية شاهقة، ضباب جوي غامض، فن رقمي عالي التفاصيل',
  '[{"key":"scene","label_ar":"المشهد","label_en":"Scene","default":"a busy night street market"},{"key":"color","label_ar":"لون الأضواء","label_en":"Light color","default":"cyan and magenta"}]'::jsonb,
  (select id from public.categories where slug = 'art-styles'),
  'cyberpunk', 'flux-schnell', ARRAY['فني', 'سايبربانك']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'podcast-cover-art', 'غلاف بودكاست', 'Podcast Cover Art',
  'غلاف مربع جذاب يناسب منصات البودكاست', 'Eye-catching square cover suited for podcast platforms',
  'modern podcast cover art design, bold {{color}} color scheme, abstract sound wave graphic element, large space for title text, professional audio branding style, square format', 'تصميم غلاف بودكاست عصري، ألوان جريئة بدرجة {{color}}، عنصر رسومي لموجات صوتية تجريدية، مساحة كبيرة لعنوان الحلقة، أسلوب هوية صوتية احترافي، مقاس مربع',
  '[{"key":"color","label_ar":"اللون","label_en":"Color","default":"deep purple and orange"}]'::jsonb,
  (select id from public.categories where slug = 'covers-posts'),
  'modern', 'flux-schnell', ARRAY['غلاف', 'بودكاست']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'ebook-cover-design', 'غلاف كتاب إلكتروني', 'Ebook Cover Design',
  'غلاف احترافي لكتاب رقمي أو دليل إرشادي', 'Professional cover for a digital book or guide',
  'professional ebook cover design about {{topic}}, minimal modern layout, {{color}} color palette, large title text space, subtle abstract background graphic, publishing quality', 'تصميم غلاف كتاب إلكتروني عن {{topic}}، تخطيط عصري بسيط، لوحة ألوان {{color}}، مساحة نص عنوان كبيرة، رسم خلفية تجريدي خفيف، جودة نشر احترافية',
  '[{"key":"topic","label_ar":"الموضوع","label_en":"Topic","default":"digital marketing"},{"key":"color","label_ar":"الألوان","label_en":"Colors","default":"navy and gold"}]'::jsonb,
  (select id from public.categories where slug = 'covers-posts'),
  'editorial', 'flux-schnell', ARRAY['غلاف', 'كتاب']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'youtube-thumbnail', 'صورة مصغرة ليوتيوب', 'YouTube Thumbnail',
  'صورة مصغرة لافتة تزيد نسبة النقر على الفيديو', 'Attention-grabbing thumbnail to boost video click-through',
  'high contrast YouTube thumbnail design about {{topic}}, bold expressive focal subject, bright {{color}} background, large readable text space, exciting energetic composition', 'تصميم صورة مصغرة ليوتيوب عالي التباين عن {{topic}}، عنصر محوري تعبيري بارز، خلفية زاهية بلون {{color}}، مساحة نص كبيرة وواضحة، تكوين حيوي ومثير',
  '[{"key":"topic","label_ar":"الموضوع","label_en":"Topic","default":"a tech review"},{"key":"color","label_ar":"لون الخلفية","label_en":"Background color","default":"bright yellow"}]'::jsonb,
  (select id from public.categories where slug = 'covers-posts'),
  'bold', 'flux-schnell', ARRAY['غلاف', 'يوتيوب']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'linkedin-banner', 'بانر لينكدإن احترافي', 'Professional LinkedIn Banner',
  'بانر بروفايل يعكس هوية احترافية على لينكدإن', 'Profile banner reflecting a professional identity on LinkedIn',
  'professional LinkedIn banner design, wide format, clean corporate {{color}} palette, subtle geometric background pattern, elegant space for name and title text, business networking style', 'تصميم بانر لينكدإن احترافي، مقاس عريض، لوحة ألوان مؤسسية نظيفة {{color}}، نمط هندسي خفيف في الخلفية، مساحة أنيقة للاسم والمسمى الوظيفي، أسلوب تواصل مهني',
  '[{"key":"color","label_ar":"الألوان","label_en":"Colors","default":"navy blue"}]'::jsonb,
  (select id from public.categories where slug = 'covers-posts'),
  'corporate', 'flux-schnell', ARRAY['غلاف', 'لينكدإن']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'event-poster-design', 'بوستر فعالية', 'Event Poster Design',
  'بوستر إعلاني جذاب للفعاليات والمؤتمرات', 'Eye-catching poster design for events and conferences',
  'vibrant event poster design for {{event}}, dynamic layered composition, bold {{color}} color scheme, large space for event details text, modern festival poster style', 'تصميم بوستر فعالية نابض بالحياة لـ{{event}}، تكوين طبقات ديناميكي، ألوان جريئة {{color}}، مساحة كبيرة لتفاصيل الفعالية، أسلوب بوستر مهرجانات عصري',
  '[{"key":"event","label_ar":"الفعالية","label_en":"Event","default":"a tech conference"},{"key":"color","label_ar":"الألوان","label_en":"Colors","default":"electric blue and purple"}]'::jsonb,
  (select id from public.categories where slug = 'covers-posts'),
  'festival', 'flux-schnell', ARRAY['غلاف', 'فعاليات']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'playlist-cover-art', 'غلاف قائمة تشغيل موسيقية', 'Music Playlist Cover Art',
  'غلاف مربع نابض بالحياة لقوائم التشغيل الموسيقية', 'Vibrant square cover art for music playlists',
  'vibrant music playlist cover art for a {{genre}} playlist, abstract flowing color shapes, {{color}} gradient palette, dynamic energetic composition, square streaming platform format', 'غلاف قائمة تشغيل موسيقية نابض بالحياة لموسيقى {{genre}}، أشكال لونية متدفقة تجريدية، لوحة تدرج {{color}}، تكوين ديناميكي حيوي، مقاس مربع لمنصات البث',
  '[{"key":"genre","label_ar":"نوع الموسيقى","label_en":"Music genre","default":"chill lofi"},{"key":"color","label_ar":"التدرج اللوني","label_en":"Gradient","default":"purple to blue"}]'::jsonb,
  (select id from public.categories where slug = 'covers-posts'),
  'abstract', 'flux-schnell', ARRAY['غلاف', 'موسيقى']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'social-profile-header', 'غلاف بروفايل تويتر/إكس', 'Twitter/X Profile Header',
  'غلاف بروفايل عريض يعكس هوية العلامة', 'Wide profile header reflecting the brand''s identity',
  'wide social media profile header design about {{topic}}, minimal modern {{color}} background, subtle brand pattern, clean composition with space for profile photo overlay, professional look', 'تصميم غلاف بروفايل عريض لمنصة تواصل عن {{topic}}، خلفية عصرية بسيطة بلون {{color}}، نمط علامة تجارية خفيف، تكوين نظيف مع مساحة لصورة البروفايل، مظهر احترافي',
  '[{"key":"topic","label_ar":"الموضوع","label_en":"Topic","default":"a design studio"},{"key":"color","label_ar":"لون الخلفية","label_en":"Background color","default":"charcoal and teal"}]'::jsonb,
  (select id from public.categories where slug = 'covers-posts'),
  'minimal', 'flux-schnell', ARRAY['غلاف', 'بروفايل']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'ramadan-greeting-post', 'منشور تهنئة رمضانية', 'Ramadan Greeting Post',
  'تصميم احتفالي بأجواء رمضان للمتاجر والعلامات', 'Festive Ramadan-themed design for stores and brands',
  'elegant Ramadan greeting design, ornate crescent moon and lantern illustration, warm {{color}} tones with gold accents, arabesque pattern details, festive Islamic aesthetic, space for greeting text', 'تصميم تهنئة رمضانية أنيق، رسم هلال وفانوس مزخرف، درجات {{color}} دافئة مع لمسات ذهبية، تفاصيل زخرفة عربية، طابع احتفالي إسلامي، مساحة لنص التهنئة',
  '[{"key":"color","label_ar":"اللون","label_en":"Color","default":"deep purple"}]'::jsonb,
  (select id from public.categories where slug = 'occasions'),
  'festive', 'flux-schnell', ARRAY['مناسبات', 'رمضان']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'eid-celebration-banner', 'بانر احتفال العيد', 'Eid Celebration Banner',
  'بانر مبهج للاحتفال بالعيد ومناسبات العروض', 'Cheerful banner for Eid celebrations and related promotions',
  'joyful Eid celebration banner design, decorative geometric Islamic patterns, bright {{color}} festive colors, fireworks and lantern illustrations, space for greeting message, high quality', 'تصميم بانر احتفال بالعيد مفعم بالبهجة، زخارف إسلامية هندسية، ألوان احتفالية زاهية {{color}}، رسومات ألعاب نارية وفوانيس، مساحة لرسالة التهنئة، جودة عالية',
  '[{"key":"color","label_ar":"الألوان","label_en":"Colors","default":"gold and green"}]'::jsonb,
  (select id from public.categories where slug = 'occasions'),
  'festive', 'flux-schnell', ARRAY['مناسبات', 'عيد']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'national-day-poster', 'بوستر اليوم الوطني', 'National Day Poster',
  'تصميم فخم يحتفي بمناسبة اليوم الوطني', 'A proud design celebrating National Day',
  'patriotic national day poster design, flag colors {{color}}, falcon and heritage pattern silhouettes, fireworks in the sky, dramatic sunset background, celebratory space themed composition', 'تصميم بوستر وطني فخم، ألوان العلم {{color}}، ظلال صقر وزخارف تراثية، ألعاب نارية في السماء، خلفية غروب درامية، تكوين احتفالي بروح المناسبة',
  '[{"key":"color","label_ar":"ألوان العلم","label_en":"Flag colors","default":"green and white"}]'::jsonb,
  (select id from public.categories where slug = 'occasions'),
  'patriotic', 'flux-schnell', ARRAY['مناسبات', 'اليوم الوطني']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'seasonal-sale-occasion', 'تصميم عروض موسم التخفيضات', 'Seasonal Sale Occasion Design',
  'تصميم موسمي حماسي لحملات التخفيضات الكبرى', 'Energetic seasonal design for major sale campaigns',
  'high energy seasonal sale campaign design for {{season}}, bold ''{{discount}}'' text placeholder, dynamic burst shapes, vibrant {{color}} color scheme, exciting retail promotion aesthetic', 'تصميم حملة تخفيضات موسمية حماسي لـ{{season}}، مساحة نصية بارزة لعبارة ''{{discount}}''، أشكال انفجارية ديناميكية، ألوان زاهية {{color}}، طابع ترويجي مثير للتجزئة',
  '[{"key":"season","label_ar":"الموسم","label_en":"Season","default":"end of season sale"},{"key":"discount","label_ar":"نسبة الخصم","label_en":"Discount","default":"UP TO 70%"},{"key":"color","label_ar":"الألوان","label_en":"Colors","default":"red and gold"}]'::jsonb,
  (select id from public.categories where slug = 'occasions'),
  'bold', 'flux-schnell', ARRAY['مناسبات', 'تخفيضات']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'graduation-announcement', 'تصميم تهنئة تخرج', 'Graduation Announcement Design',
  'تصميم أنيق للاحتفال بمناسبة التخرج', 'Elegant design celebrating a graduation milestone',
  'elegant graduation celebration design, graduation cap and diploma illustration, confetti details, soft {{color}} festive palette, space for congratulatory text, joyful academic milestone style', 'تصميم احتفالي أنيق بمناسبة التخرج، رسم قبعة تخرج وشهادة، تفاصيل قصاصات احتفالية، لوحة ألوان ناعمة {{color}}، مساحة لنص التهنئة، طابع بهيج لإنجاز أكاديمي',
  '[{"key":"color","label_ar":"الألوان","label_en":"Colors","default":"navy and gold"}]'::jsonb,
  (select id from public.categories where slug = 'occasions'),
  'festive', 'flux-schnell', ARRAY['مناسبات', 'تخرج']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'wedding-invitation-design', 'تصميم دعوة زفاف', 'Wedding Invitation Design',
  'تصميم دعوة زفاف راقٍ بلمسة عربية', 'Refined wedding invitation with an Arabic touch',
  'luxurious wedding invitation design, delicate floral {{color}} illustrations, elegant ornamental border, soft romantic color palette, space for names and date text, premium stationery style', 'تصميم دعوة زفاف فاخرة، رسومات زهور دقيقة بلون {{color}}، إطار زخرفي أنيق، لوحة ألوان رومانسية ناعمة، مساحة لاسمي العروسين والتاريخ، أسلوب قرطاسية راقٍ',
  '[{"key":"color","label_ar":"لون الزهور","label_en":"Floral color","default":"blush pink and gold"}]'::jsonb,
  (select id from public.categories where slug = 'occasions'),
  'elegant', 'flux-schnell', ARRAY['مناسبات', 'زفاف']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'new-year-celebration', 'تصميم احتفال رأس السنة', 'New Year Celebration Design',
  'تصميم احتفالي متلألئ لمناسبة رأس السنة الميلادية', 'Sparkling festive design for New Year celebrations',
  'festive New Year celebration design, glittering fireworks and confetti, bold ''{{year}}'' number typography, dark {{color}} background with sparkling light bokeh, celebratory countdown atmosphere', 'تصميم احتفالي برأس السنة، ألعاب نارية وقصاصات متلألئة، خط بارز لرقم السنة ''{{year}}''، خلفية داكنة بلون {{color}} مع إضاءة بوكيه متلألئة، أجواء عد تنازلي احتفالية',
  '[{"key":"year","label_ar":"السنة","label_en":"Year","default":"2027"},{"key":"color","label_ar":"لون الخلفية","label_en":"Background color","default":"midnight blue and gold"}]'::jsonb,
  (select id from public.categories where slug = 'occasions'),
  'festive', 'flux-schnell', ARRAY['مناسبات', 'رأس السنة']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

insert into public.prompts (
  slug, title_ar, title_en, description_ar, description_en,
  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, status
) values (
  'mothers-day-design', 'تصميم عيد الأم', 'Mother''s Day Design',
  'تصميم دافئ ورقيق للاحتفاء بعيد الأم', 'Warm gentle design celebrating Mother''s Day',
  'gentle Mother''s Day celebration design, soft blooming {{flower}} flowers, warm pastel {{color}} palette, delicate hand-drawn illustration style, tender space for a heartfelt message', 'تصميم رقيق للاحتفاء بعيد الأم، زهور {{flower}} متفتحة ناعمة، لوحة ألوان باستيل دافئة {{color}}، أسلوب رسم يدوي رقيق، مساحة حانية لرسالة من القلب',
  '[{"key":"flower","label_ar":"نوع الزهور","label_en":"Flower type","default":"roses"},{"key":"color","label_ar":"الألوان","label_en":"Colors","default":"blush pink and cream"}]'::jsonb,
  (select id from public.categories where slug = 'occasions'),
  'gentle', 'flux-schnell', ARRAY['مناسبات', 'عيد الأم']::text[], 'published'
)
on conflict (slug) do update set
  title_ar = excluded.title_ar, title_en = excluded.title_en,
  description_ar = excluded.description_ar, description_en = excluded.description_en,
  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,
  variables = excluded.variables, category_id = excluded.category_id,
  style = excluded.style, model = excluded.model, tags = excluded.tags;

update public.prompts set is_featured = true where slug in ('studio-product-white-bg', 'instagram-square-promo', 'minimal-lettermark-logo', 'corporate-headshot', '3d-render-character', 'podcast-cover-art', 'ramadan-greeting-post');
