import { writeFileSync } from "node:fs";
import { seedCategories } from "./seed-data";

function sqlString(value: string) {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlStringArray(values: string[]) {
  return `ARRAY[${values.map(sqlString).join(", ")}]::text[]`;
}

function sqlJson(value: unknown) {
  return sqlString(JSON.stringify(value));
}

const lines: string[] = [];

lines.push("-- Auto-generated by scripts/generate-seed-sql.ts — do not edit by hand.");
lines.push("-- Re-running this file is safe: categories/prompts are upserted by slug.\n");

lines.push("insert into public.categories (slug, name_ar, name_en, icon, sort_order) values");
lines.push(
  seedCategories
    .map(
      (c) =>
        `  (${sqlString(c.slug)}, ${sqlString(c.name_ar)}, ${sqlString(c.name_en)}, ${sqlString(c.icon)}, ${c.sort_order})`,
    )
    .join(",\n") + "\non conflict (slug) do update set name_ar = excluded.name_ar, name_en = excluded.name_en, icon = excluded.icon, sort_order = excluded.sort_order;\n",
);

for (const category of seedCategories) {
  for (const prompt of category.prompts) {
    lines.push(
      [
        "insert into public.prompts (",
        "  slug, title_ar, title_en, description_ar, description_en,",
        "  prompt_text_en, prompt_display_ar, variables, category_id, style, model, tags, requires_photo, status",
        ") values (",
        `  ${sqlString(prompt.slug)}, ${sqlString(prompt.title_ar)}, ${sqlString(prompt.title_en)},`,
        `  ${sqlString(prompt.description_ar)}, ${sqlString(prompt.description_en)},`,
        `  ${sqlString(prompt.prompt_text_en)}, ${sqlString(prompt.prompt_display_ar)},`,
        `  ${sqlJson(prompt.variables)}::jsonb,`,
        `  (select id from public.categories where slug = ${sqlString(category.slug)}),`,
        `  ${sqlString(prompt.style)}, ${sqlString(prompt.model)}, ${sqlStringArray(prompt.tags)}, ${prompt.requires_photo ?? false}, 'published'`,
        ")",
        "on conflict (slug) do update set",
        "  title_ar = excluded.title_ar, title_en = excluded.title_en,",
        "  description_ar = excluded.description_ar, description_en = excluded.description_en,",
        "  prompt_text_en = excluded.prompt_text_en, prompt_display_ar = excluded.prompt_display_ar,",
        "  variables = excluded.variables, category_id = excluded.category_id,",
        "  style = excluded.style, model = excluded.model, tags = excluded.tags,",
        "  requires_photo = excluded.requires_photo;\n",
      ].join("\n"),
    );
  }
}

if (seedCategories.some((c) => c.prompts.some((p) => p.is_featured))) {
  const featuredSlugs = seedCategories.flatMap((c) =>
    c.prompts.filter((p) => p.is_featured).map((p) => p.slug),
  );
  lines.push(
    `update public.prompts set is_featured = true where slug in (${featuredSlugs.map(sqlString).join(", ")});\n`,
  );
}

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), lines.join("\n"));
console.log("Wrote supabase/seed.sql");
