update public.personal_styles set prompt_body = 'Using the uploaded photo as the strict identity reference, create a collectible chibi vinyl figure of this person displayed inside its retail collector box. The figure has the signature oversized head, large round black eyes, and tiny body — but the hairstyle, beard shape, skin tone and outfit must clearly match the person in the photo so the figure is instantly recognizable. The box: premium cardboard with a large transparent window, the person''s silhouette icon and a name plate on the front, subtle geometric pattern. Scene: the boxed figure standing on a wooden collector''s shelf, soft diffused product-photography lighting, shallow depth of field, blurred shelf of other boxes behind. Ultra sharp render, vertical 3:4 format, no real brand logos anywhere.' where slug = 'funko-pop';

update public.personal_styles set prompt_body = 'Using the uploaded photo as the strict identity reference, sculpt this person as a handcrafted stop-motion clay character. Preserve the exact face structure, hairstyle, beard and skin tone translated into smooth modeling clay with subtle fingerprint impressions and tiny tool marks. Outfit: a miniature fabric-textured version of casual clothes. Set: a charming handbuilt miniature diorama room with cardboard furniture and painted backdrop, warm tungsten studio lighting with soft shadows, gentle depth of field like a real stop-motion film frame. Whimsical, warm and instantly recognizable as the same person. Vertical 3:4 format.' where slug = 'claymation';

update public.personal_styles set prompt_body = 'Using the uploaded photo as the strict identity reference, design a sticker pack sheet of six chibi cartoon versions of this person arranged in a 2x3 grid. Each sticker keeps the same recognizable hairstyle, beard shape, eyebrows and skin tone, with big expressive eyes. Six distinct emotions: laughing hard, angry with steam, crying dramatically, heart eyes in love, confident thumbs up, sleepy with a yawn. Style: clean 2D digital illustration, bold thick white outline around every sticker, soft flat pastel background, consistent character design across all six. High resolution, vertical 3:4 sheet.' where slug = 'sticker-pack';

update public.personal_styles set prompt_body = 'Using the uploaded photo as the strict identity reference, transport this person into a 1970s disco club — same exact face, hairstyle, beard and skin tone, do not alter identity. Wardrobe: tailored bell-bottom suit in deep burgundy with a wide-collar patterned silk shirt and platform shoes. Scene: mid-dance confident pose under a spinning mirror ball, colorful light beams in pink, orange and teal sweeping across a glowing dance floor, blurred dancers behind. Authentic 1970s film photography look: Kodak-style warm colors, visible grain, slight halation on lights. Shot on 50mm, waist-up composition, vertical 3:4 format.' where slug = 'disco-70s';

update public.personal_styles set prompt_body = 'Using the uploaded photo as the strict identity reference, place this person in a Victorian London street at night, 1890s — same exact face, beard and features, do not change identity or age. Wardrobe: long dark wool overcoat, waistcoat with a silver pocket-watch chain, black top hat held or worn naturally. Scene: fog rolling between gas lamps, wet cobblestones reflecting warm lamplight, a horse carriage silhouette and iron railings in the misty background. Cinematic period-drama realism: moody sepia-leaning grade, soft volumetric light through fog, sharp facial detail against atmospheric depth. 85mm portrait lens look, vertical 3:4 format.' where slug = 'victorian';

update public.personal_styles set prompt_body = 'Using the uploaded photo as the strict identity reference, portray this person as a citizen of the year 2090 — identical face, hairstyle, beard and skin tone, no identity change. Wardrobe: minimalist high-tech jacket with subtle glowing seams in cool white-blue, matte smart fabric. Scene: standing on an elevated walkway of a gleaming utopian city at dusk — flying vehicles streaking light trails, translucent holographic interfaces floating near his hand, soft reflections on glass towers. Clean cinematic sci-fi photography: crisp detail, cool color palette with warm skin tones preserved, gentle rim light from holograms. Vertical 3:4 format.' where slug = 'future-2090';

update public.personal_styles set prompt_body = 'Using the uploaded photo as the strict identity reference, create a classic 1940s film noir portrait of this person as a private detective — exact same face and features, no beautifying. Wardrobe: belted trench coat with raised collar, fedora tilted low but keeping the face clearly visible and lit. Scene: dark office at night, dramatic venetian-blind shadow stripes falling across the face and wall, thin smoke curling through a hard beam of light from the side. High-contrast black and white, deep blacks and glowing highlights, sharp skin texture, large-format vintage photography feel. Chest-up composition, vertical 3:4 format.' where slug = 'film-noir';

update public.personal_styles set prompt_body = 'Using the uploaded photo as the strict identity reference, create a surreal fine-art underwater portrait of this person — identical facial features, calm serene expression, eyes open. Scene: suspended in clear turquoise water, golden sun rays piercing down from the surface, tiny air bubbles rising, an elegant white shirt floating and rippling with the current, soft caustic light patterns dancing across the face. Dreamy ethereal mood, realistic water physics, natural skin tones with a subtle cool cast, professional underwater photography with sharp focus on the face. Vertical 3:4 format.' where slug = 'underwater';

update public.personal_styles set prompt_body = 'Using the uploaded photo as the strict identity reference, create a fine-art double exposure poster. The sharp side profile silhouette of this person — recognizable nose, beard and hairline — filled with a second exposure: a misty pine forest at dawn, low fog between trees, a flock of birds flying toward the top of the silhouette where the image dissolves into scattered particles. Background: clean minimal off-white with generous negative space. Muted cinematic palette of deep greens and soft grays, gallery-print quality, elegant and emotional. Vertical 3:4 format.' where slug = 'double-exposure';

update public.personal_styles set prompt_body = 'Using the uploaded photo as the strict identity reference, convert this person into a detailed 16-bit pixel art game character — the pixel face must clearly echo his real hairstyle, beard shape and skin tone. Composition: character select screen of a retro arcade fighting game — the character in a confident idle pose on the left, a pixelated portrait frame of his face on the right, health bar, score counter and "PLAYER 1 — READY" text as UI elements. Vibrant limited retro palette, crisp clean pixels with no blur, subtle CRT scanline effect. Vertical 3:4 format.' where slug = 'pixel-art';

update public.personal_styles set prompt_body = 'Using the uploaded photo as the strict identity reference, shoot a high-fashion streetwear editorial of this person — identical face, beard and hairstyle, confident relaxed expression. Wardrobe: oversized heavyweight hoodie in washed neutral tone, wide cargo pants, clean sneakers, no visible brand logos. Scene: narrow urban alley with colorful graffiti walls, late-afternoon hard sunlight cutting diagonal shadows, light haze in the air. Magazine-quality fashion photography: strong pose, 35mm lens, rich contrast with lifted blacks, sharp fabric texture, editorial color grade. Full-body or three-quarter composition, vertical 3:4 format.' where slug = 'streetwear';

update public.personal_styles set prompt_body = 'Using the uploaded photo as the strict identity reference, transform this person into a legendary pirate captain — exact same facial features and beard, weathered but recognizable. Wardrobe: aged leather tricorn hat, long dark captain''s coat with brass buttons, loose linen shirt, leather gloves gripping the ship''s wheel. Scene: deck of a wooden galleon in a dramatic storm — rain streaks, torn sails and ropes whipping in the wind, huge waves and lightning on the horizon, lantern glow warming one side of the face. Epic cinematic realism, movie-still quality, dramatic low angle. Vertical 3:4 format.' where slug = 'pirate-captain';

update public.personal_styles set prompt_body = 'Using the uploaded photo as the strict identity reference, portray this person as a professional race driver — identical face, hairstyle and beard, focused confident look. Wardrobe: fitted racing suit in deep red and white with generic geometric patches (no real sponsor or team logos), holding a glossy helmet under one arm. Scene: pit lane at golden hour, a sleek formula race car blurred behind him, heat shimmer over the asphalt, grandstand crowd out of focus in warm light. Sports-magazine photography: 85mm lens, shallow depth of field, crisp detail on the face and suit, dynamic warm grade. Vertical 3:4 format.' where slug = 'f1-driver';

update public.personal_styles set prompt_body = 'Using the uploaded photo as the strict identity reference, capture this person at a glamorous movie premiere — exact same face and features, confident subtle smile. Wardrobe: impeccably tailored midnight-blue tuxedo with black satin lapels, crisp white shirt, black bow tie, luxury watch. Scene: walking the red carpet, dozens of paparazzi camera flashes freezing the moment from both sides, elegant blurred step-and-repeat backdrop with abstract patterns (no real logos), velvet ropes. Celebrity editorial photography: sharp flash-lit look with glowing highlights, rich contrast, star-quality retouching that keeps real skin texture. Vertical 3:4 format.' where slug = 'red-carpet';
