-- Batch 2 ("trending") and batch 3 styles from the revised plan. Skips
-- "hug-younger-self" — it needs two source photos (adult + childhood),
-- which the current single-file upload flow and /api/personal-photos/generate
-- route don't support; that needs a dedicated feature, not a content add.
alter table public.personal_styles drop constraint if exists personal_styles_category_check;
alter table public.personal_styles add constraint personal_styles_category_check
  check (category in ('professional', 'cinematic', 'heritage', 'art', 'fun', 'trending'));

insert into public.personal_styles (slug, title_ar, title_en, tagline_ar, prompt_body, share_text_ar, category, sort_order)
values
-- batch 2: trending
('polaroid-flash', 'بولارويد الفلاش الليلي', 'Night Flash Polaroid', 'صورة بولارويد كأنها التقطت أمس في التسعينات.', 'Turn the uploaded photo into a vintage Polaroid picture: harsh direct flash at night, white Polaroid frame with a handwritten caption space, slight blur and film grain, curtain background, authentic instant-photo look, keep exact facial likeness.', 'جرّبت ستايل "بولارويد الفلاش الليلي" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'trending', 26),
('old-money', 'أولد موني أرستقراطي', 'Old Money Aesthetic', 'فخامة هادئة بلا شعارات… ستايل الطبقة العريقة.', 'Restyle the person from the uploaded photo in old money aesthetic: beige cashmere sweater over shoulders, classic country club garden backdrop, soft overcast light, muted editorial color grade, Ralph Lauren campaign vibe, keep exact facial likeness.', 'جرّبت ستايل "أولد موني أرستقراطي" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'trending', 27),
('billboard-nyc', 'وجهك على بيلبورد تايمز سكوير', 'Times Square Billboard', 'إعلانك الخاص وسط نيويورك.', 'Show a giant glowing Times Square billboard at night displaying a stylish portrait of the person from the uploaded photo, crowds and yellow cabs below, rain reflections, cinematic wide shot, keep the face on the billboard clearly recognizable.', 'جرّبت ستايل "وجهك على بيلبورد تايمز سكوير" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'trending', 28),
('private-jet', 'لايف ستايل الطائرة الخاصة', 'Private Jet Lifestyle', 'مقعدك في الجيت الخاص جاهز.', 'Place the person from the uploaded photo seated in a luxury private jet cabin: cream leather seats, champagne glass on the table, sunset through the oval window, elegant outfit, warm golden light, photorealistic, keep exact facial likeness.', 'جرّبت ستايل "لايف ستايل الطائرة الخاصة" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'trending', 29),
('marble-statue', 'تمثال رخامي في متحف', 'Marble Museum Statue', 'خلّدوك في متحف اللوفر.', 'Sculpt the person from the uploaded photo as a classical white marble statue displayed in a grand museum hall: accurate facial features carved in marble, dramatic spotlight, blurred visitors in background, ultra detailed sculpture texture.', 'جرّبت ستايل "تمثال رخامي في متحف" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'trending', 30),
('lego-minifig', 'شخصية ليغو بالعلبة', 'LEGO Minifigure', 'نسختك ليغو رسمية بعلبتها.', 'Create a LEGO minifigure version of the person from the uploaded photo inside official LEGO box packaging: matching hairstyle and outfit, fun accessories, bright product photography, box shows the character name, playful colors, recognizable stylized face.', 'جرّبت ستايل "شخصية ليغو بالعلبة" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'trending', 31),
('game-cover', 'غلاف لعبة فيديو', 'Video Game Cover', 'أنت بطل لعبة العام.', 'Design a AAA video game cover starring the person from the uploaded photo as the main character: stylized realistic game art, dramatic pose, explosive city background, bold game title space at top, console cover layout, keep facial likeness.', 'جرّبت ستايل "غلاف لعبة فيديو" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'trending', 32),
('winter-snow', 'بورتريه الثلج السينمائي', 'Cinematic Winter Snow', 'أجواء الشتاء الأوروبي… معطف طويل وثلج يتساقط.', 'Recreate the uploaded photo as a cinematic winter portrait: long dark wool coat, falling snowflakes, foggy breath, warm street lamps glowing in a European old town at dusk, shallow depth of field, keep exact facial likeness.', 'جرّبت ستايل "بورتريه الثلج السينمائي" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'trending', 33),
('lion-portrait', 'البورتريه الملكي مع الأسد', 'Royal Lion Portrait', 'أنت والأسد… هيبة ما تتكرر.', 'Epic portrait of the person from the uploaded photo standing calmly beside a majestic lion: dark smoky studio background, dramatic low-key lighting, elegant dark outfit, both looking at the camera, hyper realistic, keep exact facial likeness.', 'جرّبت ستايل "البورتريه الملكي مع الأسد" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'trending', 34),
('paris-film', 'فيلم 35mm في شوارع باريس', 'Paris 35mm Film', 'لقطة عفوية بكاميرا فيلم من مقهى باريسي.', 'Candid 35mm film photo of the person from the uploaded photo at a Parisian café terrace: morning light, croissant and espresso on the table, Haussmann buildings behind, Kodak Gold 200 film colors, natural grain, keep exact facial likeness.', 'جرّبت ستايل "فيلم 35mm في شوارع باريس" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'trending', 35),
('restore-old-photo', 'ترميم صورة قديمة', 'Restore Old Photo', 'أعد الحياة لصور عائلتك القديمة — هدية تبكي أهلك.', 'Restore and colorize the uploaded old damaged photo: remove scratches, dust and tears, sharpen facial details, natural realistic skin tones and colors, keep the original faces, clothing and composition exactly the same, museum-quality restoration.', 'رمّمت صورة أبوي القديمة ودمعت عيونه ❤️ جرب صور عائلتك 👇', 'trending', 36),
-- batch 3
('samurai', 'الساموراي', 'Samurai Warrior', 'محارب من اليابان القديمة… بوجهك.', 'Turn the person from the uploaded photo into a samurai warrior: traditional detailed armor with shoulder guards, katana held with both hands, misty bamboo forest at dawn, cinematic rim light, ultra realistic, keep exact facial likeness.', 'جرّبت ستايل "الساموراي" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'fun', 37),
('medieval-knight', 'فارس العصور الوسطى', 'Medieval Knight', 'درع كامل وسيف وقلعة خلفك.', 'Dress the person from the uploaded photo as a medieval knight in polished steel plate armor, holding a longsword, stone castle courtyard behind, dramatic torchlight, epic fantasy realism, keep exact facial likeness.', 'جرّبت ستايل "فارس العصور الوسطى" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'fun', 38),
('king-throne', 'الملك على العرش', 'King on the Throne', 'التاج والعرش… جلالتك.', 'Portray the person from the uploaded photo as a king seated on an ornate golden throne: royal velvet robe, crown, grand palace hall with columns, dramatic cinematic lighting, oil-painting-level detail but photorealistic, keep exact facial likeness.', 'جرّبت ستايل "الملك على العرش" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'fun', 39),
('cowboy', 'كاوبوي الغرب الأمريكي', 'Western Cowboy', 'غروب، غبار، وحزام مسدس.', 'Restyle the person from the uploaded photo as a western cowboy: leather hat and duster coat, dusty frontier town at sunset, warm orange backlight, squinting confident look, cinematic western film still, keep exact facial likeness.', 'جرّبت ستايل "كاوبوي الغرب الأمريكي" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'fun', 40),
('gangster-1920s', 'غانغستر العشرينات', '1920s Gangster', 'بدلة صوفية وقبعة مسطحة وأجواء غامضة.', 'Transform the person from the uploaded photo into a 1920s gangster: tweed three-piece suit, flat cap, pocket watch chain, foggy cobblestone industrial street at night, moody desaturated cinematic grade, keep exact facial likeness.', 'جرّبت ستايل "غانغستر العشرينات" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'fun', 41),
('ufc-poster', 'بوستر نزال UFC', 'UFC Fight Poster', 'اسمك على بوستر النزال الرئيسي.', 'Create a dramatic MMA fight event poster starring the person from the uploaded photo: fighter stance, subtle sweat and determination, dark arena spotlights, bold event typography space, sports poster grading, keep exact facial likeness.', 'جرّبت ستايل "بوستر نزال UFC" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'fun', 42),
('fighter-pilot', 'طيار حربي', 'Fighter Pilot', 'توب غن… نسختك.', 'Put the person from the uploaded photo in a fighter pilot flight suit and aviator sunglasses, standing on an aircraft carrier deck beside a fighter jet at golden hour, wind-blown, cinematic movie poster style, keep exact facial likeness.', 'جرّبت ستايل "طيار حربي" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'fun', 43),
('chef', 'شيف المطعم الفاخر', 'Executive Chef', 'شيف ميشلان… والمطبخ مملكتك.', 'Portray the person from the uploaded photo as an executive chef in a pristine white chef jacket, arms crossed in a high-end restaurant kitchen, flames and steam behind, editorial food-magazine lighting, keep exact facial likeness.', 'جرّبت ستايل "شيف المطعم الفاخر" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'professional', 44),
('neon-gel-studio', 'استوديو نيون ملون', 'Neon Gel Studio', 'جلسة استوديو بإضاءة ملونة تكسر الفيد.', 'Studio portrait of the person from the uploaded photo with dual color gel lighting: strong blue light from one side and hot pink from the other, dark background, light haze, fashion editorial pose, sharp details, keep exact facial likeness.', 'جرّبت ستايل "استوديو نيون ملون" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'art', 45),
('pencil-sketch', 'رسم قلم رصاص', 'Pencil Sketch', 'بورتريه مرسوم يدوياً بدقة الفنانين.', 'Convert the uploaded photo into a highly detailed graphite pencil sketch: realistic shading and cross-hatching, textured drawing paper, artist''s hand and pencil visible at the corner finishing the drawing, keep exact facial likeness.', 'جرّبت ستايل "رسم قلم رصاص" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'art', 46),
('caricature', 'كاريكاتير احترافي', 'Professional Caricature', 'نسختك المضحكة… برأس كبير وابتسامة أكبر.', 'Create a friendly professional caricature of the person from the uploaded photo: slightly exaggerated head and features while staying clearly recognizable, vibrant digital painting style, simple color background, fun expression.', 'جرّبت ستايل "كاريكاتير احترافي" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'art', 47),
('anime-hero', 'بطل أنمي شونين', 'Shonen Anime Hero', 'حلقتك الأولى تبدأ الآن.', 'Redraw the person from the uploaded photo as a shonen anime hero: dynamic pose, energy aura, spiky highlights in hair keeping original hairstyle recognizable, dramatic action background with speed lines, high quality anime key visual, keep facial likeness.', 'جرّبت ستايل "بطل أنمي شونين" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'art', 48),
('passport-pro', 'صورة رسمية للوثائق', 'Professional Passport Photo', 'صورة جواز/هوية مثالية بدون استوديو.', 'Turn the uploaded photo into a professional ID/passport photo: plain white background, even soft studio lighting, neutral expression facing camera, formal shirt, sharp focus, official document photo standards, keep exact facial likeness.', 'جرّبت ستايل "صورة رسمية للوثائق" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'professional', 49),
('wedding-groom', 'العريس يوم الزفاف', 'Wedding Day Groom', 'إطلالة يوم العمر.', 'Portray the person from the uploaded photo as an elegant groom on his wedding day: classic black tuxedo with boutonniere, luxurious wedding venue with warm candlelight and floral arch, cinematic romantic mood, keep exact facial likeness.', 'جرّبت ستايل "العريس يوم الزفاف" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'cinematic', 50),
('graduation', 'يوم التخرج', 'Graduation Day', 'القبعة والروب ولحظة الفخر.', 'Show the person from the uploaded photo as a university graduate: black cap and gown, holding a diploma, sunlit campus courtyard, confetti in the air, proud smile, warm celebratory tones, keep exact facial likeness.', 'جرّبت ستايل "يوم التخرج" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'cinematic', 51),
('luxury-car', 'مع السيارة الفاخرة', 'Luxury Supercar', 'أنت ومفتاح اللامبو.', 'Place the person from the uploaded photo leaning on a matte black luxury supercar at night: city lights bokeh, stylish outfit, low cinematic angle, reflections on the car body, high-end automotive photography, keep exact facial likeness.', 'جرّبت ستايل "مع السيارة الفاخرة" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'fun', 52)
on conflict (slug) do nothing;
