alter table public.personal_styles add column if not exists is_trending boolean not null default false;

update public.personal_styles set is_trending = true where slug = 'polaroid-flash';

insert into public.personal_styles
  (slug, title_ar, title_en, tagline_ar, prompt_body, share_text_ar, category, sort_order, is_trending, example_before_url)
values
('funko-pop', 'فانكو بوب بالعلبة', 'Funko Pop Figure', 'رأس كبير وعيون كرتونية… نسختك المجسّمة الشهيرة.', 'Create a Funko Pop style vinyl figure of the person from the uploaded photo inside its collector box: oversized head with signature style, matching hairstyle, beard and outfit, box window showing the figure, name printed on the box, product photography on a shelf, recognizable stylized face.', 'جرّبت ستايل "فانكو بوب بالعلبة" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'fun', 53, true, 'https://ocbexnlvopobemvzqsjd.supabase.co/storage/v1/object/public/personal-style-examples/before.jpg'),
('claymation', 'شخصية صلصال (كلايميشن)', 'Claymation Character', 'كأنك خرجت من فيلم أنيميشن صلصال.', 'Turn the person from the uploaded photo into a claymation stop-motion character: smooth clay texture with subtle fingerprint impressions, handcrafted miniature set background, warm playful studio lighting, Aardman-style charm, keep recognizable facial likeness.', 'جرّبت ستايل "شخصية صلصال (كلايميشن)" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'art', 54, false, 'https://ocbexnlvopobemvzqsjd.supabase.co/storage/v1/object/public/personal-style-examples/before.jpg'),
('sticker-pack', 'حزمة ستيكرات تشيبي', 'Chibi Sticker Pack', 'ستيكراتك الخاصة للواتساب — 6 انفعالات بوجهك.', 'Create a sticker pack sheet of 6 chibi versions of the person from the uploaded photo: big expressive eyes, different emotions (laughing, angry, crying, in love, thumbs up, sleepy), white outline around each sticker, flat pastel background, keep recognizable facial features and hairstyle.', 'جرّبت ستايل "حزمة ستيكرات تشيبي" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'fun', 55, true, 'https://ocbexnlvopobemvzqsjd.supabase.co/storage/v1/object/public/personal-style-examples/before.jpg'),
('disco-70s', 'ديسكو السبعينات', '70s Disco', 'بنطال شارلستون وكرة الديسكو تلمع فوقك.', 'Transform the person from the uploaded photo into a 1970s disco scene: bell-bottom suit with wide collar, platform shoes, mirror ball reflections and colorful dance floor lights, retro film colors and grain, confident dance pose, keep exact facial likeness.', 'جرّبت ستايل "ديسكو السبعينات" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'cinematic', 56, false, 'https://ocbexnlvopobemvzqsjd.supabase.co/storage/v1/object/public/personal-style-examples/before.jpg'),
('victorian', 'شوارع لندن الفيكتورية', 'Victorian London', 'سافر لعام 1890… معطف طويل وشوارع مبللة وفوانيس غاز.', 'Place the person from the uploaded photo in a Victorian London street at night, 1890s: long dark overcoat and top hat, gas lamps glowing through fog, wet cobblestones, horse carriage silhouette behind, moody sepia-toned cinematic realism, keep exact facial likeness.', 'جرّبت ستايل "شوارع لندن الفيكتورية" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'heritage', 57, false, 'https://ocbexnlvopobemvzqsjd.supabase.co/storage/v1/object/public/personal-style-examples/before.jpg'),
('future-2090', 'نسختك من عام 2090', 'Year 2090', 'كيف ستبدو صورتك بعد 65 سنة من التكنولوجيا؟', 'Show the person from the uploaded photo as a citizen of year 2090: sleek futuristic clothing with soft glowing seams, holographic interfaces floating around, gleaming utopian city with flying vehicles behind, clean sci-fi photography, keep exact facial likeness.', 'جرّبت ستايل "نسختك من عام 2090" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'cinematic', 58, true, 'https://ocbexnlvopobemvzqsjd.supabase.co/storage/v1/object/public/personal-style-examples/before.jpg'),
('film-noir', 'المحقق نوار', 'Film Noir Detective', 'دخان، ظلال، وقضية غامضة تنتظرك.', 'Classic 1940s film noir portrait of the person from the uploaded photo as a detective: trench coat and fedora, dramatic venetian blind shadows across the face, cigarette smoke curling in a beam of light, high contrast black and white, keep exact facial likeness.', 'جرّبت ستايل "المحقق نوار" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'cinematic', 59, false, 'https://ocbexnlvopobemvzqsjd.supabase.co/storage/v1/object/public/personal-style-examples/before.jpg'),
('underwater', 'بورتريه تحت الماء', 'Underwater Portrait', 'لقطة سريالية تحبس الأنفاس… حرفياً.', 'Surreal underwater portrait of the person from the uploaded photo: calm expression, sun rays piercing turquoise water, tiny air bubbles, floating fabric of an elegant shirt, soft caustic light patterns on the face, dreamy fine-art photography, keep exact facial likeness.', 'جرّبت ستايل "بورتريه تحت الماء" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'art', 60, false, 'https://ocbexnlvopobemvzqsjd.supabase.co/storage/v1/object/public/personal-style-examples/before.jpg'),
('double-exposure', 'دبل إكسبوجر فني', 'Artistic Double Exposure', 'صورتك تحكي قصتين في لقطة واحدة.', 'Create an artistic double exposure: the silhouette profile of the person from the uploaded photo blended with a misty pine forest and flying birds inside the silhouette, minimal white background, fine art poster style, keep the facial profile recognizable.', 'جرّبت ستايل "دبل إكسبوجر فني" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'art', 61, false, 'https://ocbexnlvopobemvzqsjd.supabase.co/storage/v1/object/public/personal-style-examples/before.jpg'),
('pixel-art', 'بكسل آرت الألعاب القديمة', 'Retro Pixel Art', 'نسختك من أتاري وسيغا.', 'Convert the person from the uploaded photo into detailed 16-bit pixel art: retro video game character style, matching hairstyle, beard and outfit, arcade game background with health bar and score UI, vibrant limited color palette, recognizable stylized face.', 'جرّبت ستايل "بكسل آرت الألعاب القديمة" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'art', 62, true, 'https://ocbexnlvopobemvzqsjd.supabase.co/storage/v1/object/public/personal-style-examples/before.jpg'),
('streetwear', 'ستريت وير إديتوريال', 'Streetwear Editorial', 'إطلالة مجلات الموضة الشبابية.', 'Urban streetwear editorial photo of the person from the uploaded photo: oversized designer hoodie and cargo pants, standing in a graffiti alley with dramatic sunlight and long shadows, magazine fashion pose, sharp high-fashion retouching, keep exact facial likeness.', 'جرّبت ستايل "ستريت وير إديتوريال" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'professional', 63, false, 'https://ocbexnlvopobemvzqsjd.supabase.co/storage/v1/object/public/personal-style-examples/before.jpg'),
('pirate-captain', 'قبطان القراصنة', 'Pirate Captain', 'سفينتك وكنزك وبحر غاضب خلفك.', 'Turn the person from the uploaded photo into a pirate captain: weathered leather tricorn hat and long coat, standing on a ship deck in a storm, ropes and sails behind, gold coins in hand, dramatic cinematic lighting, ultra realistic, keep exact facial likeness.', 'جرّبت ستايل "قبطان القراصنة" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'fun', 64, false, 'https://ocbexnlvopobemvzqsjd.supabase.co/storage/v1/object/public/personal-style-examples/before.jpg'),
('f1-driver', 'سائق فورمولا 1', 'F1 Driver', 'خوذتك تحت إبطك وسيارة السباق خلفك.', 'Portray the person from the uploaded photo as a Formula 1 driver: racing suit with sponsor patches, helmet under one arm, standing in the pit lane beside a race car, blurred crowd and track behind, golden afternoon light, sports magazine photography, keep exact facial likeness.', 'جرّبت ستايل "سائق فورمولا 1" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'fun', 65, false, 'https://ocbexnlvopobemvzqsjd.supabase.co/storage/v1/object/public/personal-style-examples/before.jpg'),
('red-carpet', 'السجادة الحمراء', 'Red Carpet Premiere', 'فلاشات المصورين كلها عليك.', 'Show the person from the uploaded photo on a movie premiere red carpet: elegant midnight-blue tuxedo, paparazzi camera flashes from all sides, step-and-repeat backdrop with blurred logos, confident celebrity pose, glamorous editorial lighting, keep exact facial likeness.', 'جرّبت ستايل "السجادة الحمراء" على صورتي والنتيجة خيال 🤯 المنصة عربية ومجانية — ارفع صورتك وشوف بنفسك 👇', 'cinematic', 66, false, 'https://ocbexnlvopobemvzqsjd.supabase.co/storage/v1/object/public/personal-style-examples/before.jpg')
on conflict (slug) do nothing;
