-- Replace the single generic "football-star" style with 5 specific
-- team/national-team variants — the generic one produced an arbitrary
-- kit design since the prompt never named a team.
update personal_styles set is_active = false where slug = 'football-star';

insert into public.personal_styles (slug, title_ar, title_en, tagline_ar, prompt_body, share_text_ar, category, sort_order)
values
('real-madrid-star', 'نجم ريال مدريد', 'Real Madrid Star', 'قميص الملكي الأبيض... وأنت بطل الملعب.', 'Create an official Real Madrid football club player portrait of the person from the uploaded photo: iconic all-white home kit with subtle navy and gold trim, arms crossed, confident pose, stadium tunnel background with dramatic spotlights and blurred crowd, sports magazine retouching, keep exact facial likeness.', 'من سيلفي عادية لنجم ريال مدريد 👑⚽ جرّب صورتك بنفسك 👇', 'fun', 21),
('barcelona-star', 'نجم برشلونة', 'Barcelona Star', 'الألوان البرشلونية... وأنت النجم.', 'Create an official FC Barcelona football club player portrait of the person from the uploaded photo: iconic blue and garnet striped home kit, arms crossed, confident pose, stadium tunnel background with dramatic spotlights and blurred crowd, sports magazine retouching, keep exact facial likeness.', 'من سيلفي عادية لنجم برشلونة 🔵🔴⚽ جرّب صورتك بنفسك 👇', 'fun', 22),
('morocco-star', 'نجم المنتخب المغربي', 'Morocco National Team Star', 'أسود الأطلس... وأنت واحد منهم.', 'Create an official Morocco national football team player portrait of the person from the uploaded photo: red kit with green trim, national team crest, arms crossed, confident pose, stadium background with Moroccan flag colors and blurred cheering crowd, sports magazine retouching, keep exact facial likeness.', 'من سيلفي عادية لنجم المنتخب المغربي 🇲🇦⚽ جرّب صورتك بنفسك 👇', 'fun', 23),
('egypt-star', 'نجم المنتخب المصري', 'Egypt National Team Star', 'الفراعنة... وأنت نجمهم الجديد.', 'Create an official Egypt national football team player portrait of the person from the uploaded photo: red kit with black and white trim, national team crest, arms crossed, confident pose, stadium background with Egyptian flag colors and blurred cheering crowd, sports magazine retouching, keep exact facial likeness.', 'من سيلفي عادية لنجم المنتخب المصري 🇪🇬⚽ جرّب صورتك بنفسك 👇', 'fun', 24),
('palestine-star', 'نجم منتخب فلسطين', 'Palestine National Team Star', 'الكوفية والعلم... وأنت نجم المنتخب.', 'Create a dignified official Palestine national football team player portrait of the person from the uploaded photo: kit in the colors of the Palestinian flag (black, white, green, red), national team crest, arms crossed, confident proud pose, stadium background with Palestinian flag colors and blurred cheering crowd, sports magazine retouching, keep exact facial likeness.', 'من سيلفي عادية لنجم منتخب فلسطين 🇵🇸⚽ جرّب صورتك بنفسك 👇', 'fun', 25)
on conflict (slug) do nothing;
